[package]
name = "asgard-discord-bot-rust"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
parsercher = "3.1.6"
raxios = "0.5.2"
regex = "1.7.1"
serde = "1.0.152"
serenity = "0.11"
tokio = {version="1.24.1",features = ["rt","full"]}
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.12.0"
html5ever = "0.26.0"
tendril = "0.4.3"
tugger = "0.18.0"
