[package]
name = "asgard-discord-bot-rust"
version = "1.0.13"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
parsercher = "3.1.6"
raxios = "0.5.2"
regex = "1.8.4"
serde = "1.0.164"
serenity = "0.11.6"
tokio = { version = "1.29.1", features = ["rt", "full"] }
reqwest = { version = "0.11.18", features = ["blocking"] }