[package]
name = "asgard-discord-bot-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
parsercher = "3.1.6"
raxios = "0.5.2"
regex = "1.7.1"
serde = "1.0.152"
serenity = "0.11"
tokio = {version="1.24.1",features = ["rt"]}

